[versions]
storage = "3.4.0"

[libraries]
paper-base = { group = "io.papermc.paper", name = "paper-api", version = "1.20.1-R0.1-SNAPSHOT" }
annotations = { group = "org.jetbrains", name = "annotations", version = "24.0.1" }